apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: vpc
  # lables of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: blue
spec:
    replicas: 1
    selector:
      matchLabels:
        app: backend
        tier: backend
        project: expense 
    template:
      metadata:
        labels:
          app: backend
          tier: backend 
          project: expense 
      spec:
        containers:
        - name: nginx
          image: saimaddala/backend:1.0.1
